[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.16"

[[constraint]]
  name = "github.com/containers/image"
  version = "1.3.0"

[[constraint]]
  name = "github.com/mattn/go-zglob"
  version = "0.0.1"

[[constraint]]
  name = "github.com/mholt/archiver"
  version = "3.1.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[override]]
  name = "github.com/docker/docker"
  revision = "6e3113f700dea1bf2785d94731b4b5a1e602d9ab"

[[override]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"
